export const courseOverview = {
  duration: "8 weeks",
  cadence: "5 guided sessions per week",
  intensity: "Advanced / interview calibration",
  dailyFlow: [
    "10 min: recall the core invariants from yesterday",
    "20 min: learn the mental model and failure boundaries",
    "20 min: sketch the design trade-offs from memory",
    "10 min: answer the checkpoint as if you were in an interview",
  ],
};

export const tracks = [
  "Foundations",
  "Data flow",
  "Storage",
  "Compute",
  "Caching",
  "Reliability",
  "Streaming",
  "Case study",
];

export const toolkitPrompts = [
  {
    title: "Invariant first",
    body: "Before naming technologies, state the two or three invariants the system must preserve under load, failure, and recovery.",
  },
  {
    title: "Latency budget",
    body: "Split end-to-end latency into hops, then ask what is on the critical path and which hops can be hidden, batched, or parallelized.",
  },
  {
    title: "Write path pressure",
    body: "For every write-heavy design, ask where backpressure appears first: coordinators, logs, compaction, indexes, or network egress.",
  },
  {
    title: "Failure narrative",
    body: "Explain what happens during partial failures, stale metadata, retries, and region loss. Interviewers often grade depth from this explanation.",
  },
];

export const courseWeeks = [
  {
    week: 1,
    track: "Foundations",
    title: "Performance envelopes and system boundaries",
    focus: "Build a precise language for scale, SLOs, and bottleneck hunting.",
    lessons: [
      {
        day: "Day 1",
        title: "Translate product needs into engineering budgets",
        outcome: "Derive QPS, storage growth, fan-out, and tail-latency targets from ambiguous product requirements.",
        depth: "Use throughput, concurrency, and object-size estimates to create a range instead of a single point estimate; discuss how uncertainty changes architecture choices.",
        drills: [
          "Estimate read/write mix for a social feed and a chat product.",
          "Turn a 300 ms p99 target into per-hop latency budgets.",
        ],
        advancedNote: "Strong candidates explain why the same average load can still fail once burstiness, coordinated omission, and queue buildup are introduced.",
        checkpoint: "How would your design change if 90% of traffic arrives in a 10-minute burst every hour?",
      },
      {
        day: "Day 2",
        title: "Reason about queueing instead of raw averages",
        outcome: "Explain why utilization close to saturation breaks latency before raw capacity is exhausted.",
        depth: "Model the system as arrival rate versus service rate, then connect rising queue depth to tail-latency amplification and retry storms.",
        drills: [
          "Compare a service at 50% versus 85% utilization.",
          "Explain why autoscaling can lag behind spiky traffic.",
        ],
        advancedNote: "Mention Little’s Law and why request shaping, admission control, and load shedding are often more effective than blindly adding workers.",
        checkpoint: "What metrics tell you that queueing, not CPU, is your true bottleneck?",
      },
      {
        day: "Day 3",
        title: "Draw the critical path with confidence",
        outcome: "Identify synchronous and asynchronous edges in a design and explain their impact on p99 latency.",
        depth: "Separate user-visible critical path from side effects like analytics, indexing, or fan-out and justify what can be decoupled.",
        drills: [
          "Sketch the write path for URL shortening.",
          "Classify each dependency as blocking or deferrable.",
        ],
        advancedNote: "Depth comes from calling out hidden costs such as TLS handshakes, cache misses, cross-AZ hops, and metadata lookups.",
        checkpoint: "Which part of a write pipeline would you remove from the synchronous path first, and why?",
      },
      {
        day: "Day 4",
        title: "Separate control plane and data plane",
        outcome: "Use plane separation to explain scalability, blast radius, and operational risk.",
        depth: "Map who makes decisions, who serves data, and how stale control-plane state can affect the data plane under change or failure.",
        drills: [
          "Compare service discovery versus request serving paths.",
          "Discuss cache invalidation metadata as a control-plane concern.",
        ],
        advancedNote: "Interviewers like hearing how control-plane overload can indirectly break healthy serving nodes through bad routing or config churn.",
        checkpoint: "Why is a control-plane outage often survivable for reads but not always for writes?",
      },
      {
        day: "Day 5",
        title: "Capstone: dissect a rate limiter end to end",
        outcome: "Apply the week’s tools to a compact but realistic design.",
        depth: "Estimate load, choose the request path, identify shared state, and explain how the limiter behaves during partitions and hot keys.",
        drills: [
          "Contrast token bucket and sliding window at high scale.",
          "Decide what should stay local versus centralized.",
        ],
        advancedNote: "Push beyond algorithms and describe consistency expectations for global versus per-node limits.",
        checkpoint: "When does eventual consistency make a rate limiter unacceptable?",
      },
    ],
  },
  {
    week: 2,
    track: "Data flow",
    title: "Partitioning, replication, and consistency",
    focus: "Build strong intuition for how distributed state moves and diverges.",
    lessons: [
      {
        day: "Day 1",
        title: "Choose partition keys that survive growth",
        outcome: "Evaluate partition strategies using cardinality, access skew, and rebalancing cost.",
        depth: "Explain the difference between even hashing and domain-aware sharding, and when tenant or locality constraints dominate.",
        drills: [
          "Pick partition keys for ride matching and object storage metadata.",
          "Name symptoms of a slowly developing hot partition.",
        ],
        advancedNote: "Deep answers mention secondary hotspots caused by indexes, cache locality, and leader concentration even after primary sharding looks balanced.",
        checkpoint: "How would you detect a hot key before customer latency degrades?",
      },
      {
        day: "Day 2",
        title: "Understand leader-based replication under stress",
        outcome: "Explain commit flow, lag, failover, and replica read staleness.",
        depth: "Follow a write from client to leader to followers, then reason about acknowledgement policies and the trade-off between durability and latency.",
        drills: [
          "Compare write concern of one replica versus quorum.",
          "Describe what changes during leader election.",
        ],
        advancedNote: "Mention replication slots, WAL pressure, and why failover freshness depends on both transport lag and apply lag.",
        checkpoint: "Why can a follower appear healthy while still being unsafe for bounded-staleness reads?",
      },
      {
        day: "Day 3",
        title: "Use quorum math carefully",
        outcome: "State what read and write quorums guarantee and what they do not.",
        depth: "Explain overlap requirements, sloppy quorums, hinted handoff, and why monotonic reads are not automatic.",
        drills: [
          "Reason through R=2, W=2, N=3.",
          "List anomalies possible during partitions.",
        ],
        advancedNote: "Advanced depth means explaining why real systems with repair lag and clock uncertainty can violate the simple textbook story.",
        checkpoint: "What user-visible anomalies can still happen with quorum reads?",
      },
      {
        day: "Day 4",
        title: "Design for repair, not just for steady state",
        outcome: "Account for anti-entropy, rebalancing, and replica rebuilds in your architecture.",
        depth: "Quantify the background bandwidth and disk pressure caused by repair work and relate it to peak load planning.",
        drills: [
          "Explain Merkle-tree-based repair at a high level.",
          "Estimate how long a 2 TB replica rebuild takes.",
        ],
        advancedNote: "This is where senior candidates call out that recovery traffic can be the real capacity planning driver.",
        checkpoint: "How do you stop repair work from destroying foreground latency?",
      },
      {
        day: "Day 5",
        title: "Capstone: globally distributed metadata service",
        outcome: "Choose between strong and relaxed consistency for metadata that gates data access.",
        depth: "Model who needs freshness, what can tolerate staleness, and which operations need linearizable coordination.",
        drills: [
          "Split namespace updates from blob reads.",
          "Define failure behavior during region isolation.",
        ],
        advancedNote: "Use fencing tokens or version epochs in your explanation when multiple writers or failovers are possible.",
        checkpoint: "What is the cheapest place to pay the strong-consistency cost in this design?",
      },
    ],
  },
  {
    week: 3,
    track: "Storage",
    title: "Storage engines, indexes, and data layout",
    focus: "Explain what happens below the API when data lands on disk.",
    lessons: [
      {
        day: "Day 1",
        title: "Compare B-trees and LSM trees beyond buzzwords",
        outcome: "Choose storage engines based on write amplification, read patterns, and compaction behavior.",
        depth: "Describe how mutable page updates differ from log-structured ingestion and connect that to SSD wear, tail latencies, and range scans.",
        drills: [
          "Pick an engine for ledgers versus logs.",
          "List read paths for point lookups in each engine.",
        ],
        advancedNote: "Depth means bringing up bloom filters, memtables, SSTable levels, and the hidden cost of compaction debt.",
        checkpoint: "Why can an LSM system regress suddenly even when average write load looks safe?",
      },
      {
        day: "Day 2",
        title: "Understand secondary indexes as first-class write load",
        outcome: "Reason about the operational cost of indexes, not just their query benefits.",
        depth: "Explain write fan-out, index maintenance ordering, and why low-selectivity indexes often punish ingestion while helping few queries.",
        drills: [
          "Design indexes for a time-series query API.",
          "Identify which index you would drop first under pressure.",
        ],
        advancedNote: "Great answers mention covering indexes, index-only reads, and the cost of maintaining ordering across partitions.",
        checkpoint: "How do secondary indexes change your partitioning strategy?",
      },
      {
        day: "Day 3",
        title: "Use TTL, retention, and compaction as design primitives",
        outcome: "Treat data lifecycle policies as core architecture, especially for logs and telemetry.",
        depth: "Discuss tombstones, segment rollovers, retention windows, and why deletion semantics affect both storage cost and read amplification.",
        drills: [
          "Model a 30-day metrics retention policy.",
          "Explain the effect of tombstones on range queries.",
        ],
        advancedNote: "Connect retention to compliance, cold storage offload, and the need for predictable compaction windows.",
        checkpoint: "When does soft delete become more dangerous than hard delete?",
      },
      {
        day: "Day 4",
        title: "Model schema evolution under continuous deployment",
        outcome: "Explain how to roll forward safely when readers and writers are on mixed versions.",
        depth: "Cover backward and forward compatibility, dual writes, shadow reads, and contract testing between services.",
        drills: [
          "Plan a zero-downtime field migration.",
          "Spot the dangers of writing new enum values too early.",
        ],
        advancedNote: "Depth shows up when you discuss irreversible migrations and how to escape them with versioned readers or append-only models.",
        checkpoint: "Why are destructive schema changes usually operational risks instead of coding risks?",
      },
      {
        day: "Day 5",
        title: "Capstone: event store for audit-grade history",
        outcome: "Design an append-heavy system that supports immutable reads and selective projections.",
        depth: "Choose storage layout, indexing, retention policy, and projection update strategy for replayable history.",
        drills: [
          "Decide where ordering guarantees matter.",
          "Separate primary history from query-optimized views.",
        ],
        advancedNote: "Use this capstone to mention idempotency keys, exactly-once illusions, and replay blast radius.",
        checkpoint: "How would you rehydrate downstream projections after a bug in event processing?",
      },
    ],
  },
  {
    week: 4,
    track: "Compute",
    title: "Compute tiers, jobs, and asynchronous pipelines",
    focus: "Choose the right execution model for latency-sensitive and batch work.",
    lessons: [
      {
        day: "Day 1",
        title: "Separate online serving from offline throughput",
        outcome: "Explain why latency-optimized and throughput-optimized compute pools should evolve independently.",
        depth: "Contrast request/response services, worker queues, and scheduled compute with respect to autoscaling signals and failure semantics.",
        drills: [
          "Classify feed fan-out, fraud scoring, and report generation.",
          "Explain why retries behave differently in each tier.",
        ],
        advancedNote: "Call out head-of-line blocking, noisy neighbors, and how shared infrastructure can hide priority inversion.",
        checkpoint: "Why does moving work to a queue solve some latency issues but create new correctness risks?",
      },
      {
        day: "Day 2",
        title: "Design idempotent jobs that can be retried forever",
        outcome: "Build job pipelines that tolerate duplicates, reordering, and delayed execution.",
        depth: "Model operation keys, dedup windows, and the difference between side effects that are naturally idempotent versus those that require explicit state.",
        drills: [
          "Add idempotency to payment webhook processing.",
          "Explain why at-least-once delivery is often enough with good design.",
        ],
        advancedNote: "Strong answers include poison-message handling, replay visibility, and operator controls for stuck jobs.",
        checkpoint: "What is the cheapest way to make a non-idempotent downstream API safe enough?",
      },
      {
        day: "Day 3",
        title: "Use backpressure instead of unbounded buffering",
        outcome: "Detect and control overload in message-driven systems.",
        depth: "Connect queue depth, consumer lag, retry policy, and dead-letter routing to real throughput limits.",
        drills: [
          "Sketch worker autoscaling from lag.",
          "Choose where to drop low-value work under sustained overload.",
        ],
        advancedNote: "Mention credit-based flow control, bounded in-memory queues, and why backpressure signals must be fast and local.",
        checkpoint: "How can retries create more load than the original traffic spike?",
      },
      {
        day: "Day 4",
        title: "Orchestrate long-running workflows without losing state",
        outcome: "Reason about step orchestration, compensating actions, and workflow durability.",
        depth: "Compare choreography, explicit state machines, and durable workflow engines for multi-step business processes.",
        drills: [
          "Model an order pipeline with inventory, payment, and shipment.",
          "Identify which steps need compensation instead of rollback.",
        ],
        advancedNote: "Depth appears when you explain why distributed transactions are rarely the operationally simplest answer.",
        checkpoint: "When is a saga easier to operate than a two-phase commit system?",
      },
      {
        day: "Day 5",
        title: "Capstone: media processing pipeline",
        outcome: "Design a high-throughput asynchronous pipeline with visible progress and strong failure handling.",
        depth: "Separate ingest, transform, metadata, and delivery while preventing duplicate work and unbounded queue growth.",
        drills: [
          "Plan retries for CPU-heavy transcoding jobs.",
          "Choose when users should see eventual versus immediate status.",
        ],
        advancedNote: "Mention checkpointing partial work and precomputing popular renditions to reduce cold-start latency.",
        checkpoint: "How would you keep the control plane responsive during a huge upload spike?",
      },
    ],
  },
  {
    week: 5,
    track: "Caching",
    title: "Caching, contention, and hot-path optimization",
    focus: "Treat caches as consistency tools, not just speed layers.",
    lessons: [
      {
        day: "Day 1",
        title: "Pick the right cache layer for the miss penalty",
        outcome: "Choose between client, edge, service, and database-adjacent caches based on who pays the miss cost.",
        depth: "Explain cache locality, invalidation authority, and what happens when popular objects expire simultaneously.",
        drills: [
          "Place caches for a product details page.",
          "Contrast read-through and cache-aside patterns.",
        ],
        advancedNote: "Senior-level depth includes admission policies, negative caching, and request coalescing on misses.",
        checkpoint: "Why is the cache closest to the user not always the best place to store dynamic state?",
      },
      {
        day: "Day 2",
        title: "Avoid stampedes and thundering herds",
        outcome: "Protect hot paths when cached data expires or gets evicted.",
        depth: "Use jittered TTLs, single-flight, stale-while-revalidate, and background refresh to smooth load shocks.",
        drills: [
          "Design cache behavior for a flash-sale product page.",
          "Explain why synchronized TTLs are dangerous.",
        ],
        advancedNote: "Mention that cache stampedes often reveal deeper issues like expensive cold-start queries or poor key cardinality.",
        checkpoint: "What is the trade-off between stale-while-revalidate and strict freshness?",
      },
      {
        day: "Day 3",
        title: "Handle hot keys and skew deliberately",
        outcome: "Recognize when a few keys dominate traffic and apply targeted mitigation.",
        depth: "Discuss replication, local hot-item caching, request collapsing, and whether the root cause is popularity or bad key design.",
        drills: [
          "Mitigate a celebrity-profile hot key.",
          "Choose between per-node replication and sharding refinement.",
        ],
        advancedNote: "Deep answers mention coordinated write invalidation cost and how hot-key mitigation can complicate consistency guarantees.",
        checkpoint: "When would you choose to deliberately serve stale data for a hot key?",
      },
      {
        day: "Day 4",
        title: "Measure cache health with the right signals",
        outcome: "Use miss ratio, byte hit rate, origin load, and tail latency together instead of relying on hit rate alone.",
        depth: "Explain why a high hit rate can still hide poor user experience if the remaining misses are the expensive ones.",
        drills: [
          "Build a dashboard for a read-heavy API.",
          "Interpret a rising hit rate with worsening p99 latency.",
        ],
        advancedNote: "Mention warmup behavior, eviction churn, and multi-tier caches where upstream misses are masked by downstream hits.",
        checkpoint: "Which cache metric would you optimize first for an expensive search endpoint?",
      },
      {
        day: "Day 5",
        title: "Capstone: build a resilient feed-read path",
        outcome: "Combine cache layers, fan-out decisions, and consistency choices into one coherent design.",
        depth: "Choose what to precompute, what to materialize on demand, and how to keep the hottest read path smooth during bursts.",
        drills: [
          "Reason about feed fan-out on write versus read.",
          "Pick cache keys and invalidation triggers.",
        ],
        advancedNote: "Use the capstone to contrast celebrity skew with long-tail users and to discuss partial degradation modes.",
        checkpoint: "How would you degrade gracefully if cache invalidation falls behind?",
      },
    ],
  },
  {
    week: 6,
    track: "Reliability",
    title: "Reliability engineering and multi-region design",
    focus: "Practice failure-first explanations that interviewers trust.",
    lessons: [
      {
        day: "Day 1",
        title: "Move from redundancy to failure isolation",
        outcome: "Design redundancy that actually reduces correlated failure risk.",
        depth: "Separate replication for durability from isolation for availability, and discuss dependencies like DNS, config stores, and shared queues.",
        drills: [
          "Find hidden shared dependencies in a regional service.",
          "Explain why active-active is not automatically safer.",
        ],
        advancedNote: "Highlight blast radius, control-plane coupling, and the operational tax of duplicate capacity.",
        checkpoint: "What dependency is most often forgotten in multi-region interviews?",
      },
      {
        day: "Day 2",
        title: "Use timeouts, retries, and circuit breaking together",
        outcome: "Explain how resilience controls interact rather than listing them in isolation.",
        depth: "Connect timeout budgets, retry fan-out, jitter, hedging, and admission control to overload behavior.",
        drills: [
          "Tune a service calling three downstream dependencies.",
          "Explain when hedged requests help and when they hurt.",
        ],
        advancedNote: "The strongest answers mention retry budgets and client coordination to stop systemic overload amplification.",
        checkpoint: "Why can a well-meant retry policy trigger a regional incident?",
      },
      {
        day: "Day 3",
        title: "Design observability around questions, not dashboards",
        outcome: "Select logs, metrics, and traces that support design decisions and fast incident diagnosis.",
        depth: "Define golden signals, cardinality boundaries, and sampling strategy for both steady state and incidents.",
        drills: [
          "Instrument a queue-backed write pipeline.",
          "Choose which dimensions deserve high-cardinality tags.",
        ],
        advancedNote: "Deep answers explain cost-aware observability and why missing exemplars or trace linkage slows root cause analysis.",
        checkpoint: "What telemetry would prove a partition is harming freshness before it harms availability?",
      },
      {
        day: "Day 4",
        title: "Plan disaster recovery as a workload migration problem",
        outcome: "Explain RPO, RTO, data catch-up, and customer-level failover consequences.",
        depth: "Treat failover as a write-routing, cache-warming, and dependency-readiness problem rather than a simple DNS switch.",
        drills: [
          "Walk through region evacuation for a write-heavy API.",
          "Estimate recovery lag after log shipping.",
        ],
        advancedNote: "Depth shows when you discuss dark capacity, safety checks, and why failback is often harder than failover.",
        checkpoint: "How do you prove your backup region can handle real production shape, not just total QPS?",
      },
      {
        day: "Day 5",
        title: "Capstone: globally available notification platform",
        outcome: "Balance latency, regional resilience, and delivery guarantees across channels.",
        depth: "Design message ingress, channel fan-out, deduplication, and regional fallback while controlling operator complexity.",
        drills: [
          "Choose where to terminate user requests.",
          "Define which guarantees differ for email, push, and SMS.",
        ],
        advancedNote: "Great answers cover provider backpressure, per-channel rate limits, and auditability requirements.",
        checkpoint: "Where would you store delivery state if providers can respond out of order?",
      },
    ],
  },
  {
    week: 7,
    track: "Streaming",
    title: "Streaming, analytics, and near-real-time systems",
    focus: "Explain ordering, lateness, and serving patterns for continuous data.",
    lessons: [
      {
        day: "Day 1",
        title: "Distinguish logs, queues, and streams",
        outcome: "Choose the right abstraction for event transport and replay.",
        depth: "Compare retention, ordering scope, fan-out cost, and consumer independence across message queues and append logs.",
        drills: [
          "Pick transport for clickstream versus payment confirmation.",
          "Explain the serving impact of replayability.",
        ],
        advancedNote: "Mention consumer group rebalancing, partition ordering, and the hidden operational overhead of long retention.",
        checkpoint: "Why is replay a product feature for some systems and a liability for others?",
      },
      {
        day: "Day 2",
        title: "Handle event time, lateness, and windowing",
        outcome: "Explain how time semantics change analytics correctness.",
        depth: "Contrast processing time and event time, then reason about watermarks, late arrivals, and correction strategies.",
        drills: [
          "Window a metrics pipeline with 5-minute buckets.",
          "Describe how mobile offline clients create late events.",
        ],
        advancedNote: "Deeper answers describe how correction cascades into dashboards, alerts, and downstream derived tables.",
        checkpoint: "When is approximate freshness better than exact but delayed results?",
      },
      {
        day: "Day 3",
        title: "Build materialized views you can trust",
        outcome: "Design derived datasets that stay query-friendly without losing lineage.",
        depth: "Explain how checkpoints, reprocessing, and versioned pipelines keep serving layers correct over time.",
        drills: [
          "Design a rolling top-K leaderboard.",
          "Separate raw events from pre-aggregated views.",
        ],
        advancedNote: "Mention dual-running new pipelines and verifying results against historical replays before cutover.",
        checkpoint: "How do you repair a derived table after discovering a bug in transformation logic?",
      },
      {
        day: "Day 4",
        title: "Use approximate algorithms strategically",
        outcome: "Justify sketches, sampling, and probabilistic structures in interview designs.",
        depth: "Discuss where exactness is unnecessary, how error bounds are communicated, and how approximate structures reduce cost at scale.",
        drills: [
          "Choose between HyperLogLog and exact distinct counts.",
          "Explain bloom filters in a storage or cache design.",
        ],
        advancedNote: "Strong answers note mergeability, memory ceilings, and how approximation affects downstream business decisions.",
        checkpoint: "What would make an approximate answer unacceptable even if it saves huge cost?",
      },
      {
        day: "Day 5",
        title: "Capstone: metrics and alerting platform",
        outcome: "Design a streaming ingestion and query system with retention tiers and multi-tenant isolation.",
        depth: "Combine ingestion, rollups, storage, and alert evaluation while controlling cardinality explosions.",
        drills: [
          "Partition metric writes and label indexes.",
          "Plan hot retention and cold retention tiers.",
        ],
        advancedNote: "Use the capstone to discuss high-cardinality labels, pre-aggregation, and why alert correctness is both a stream and serving problem.",
        checkpoint: "How do you prevent a single tenant’s labels from destabilizing the entire platform?",
      },
    ],
  },
  {
    week: 8,
    track: "Case study",
    title: "Interview synthesis and full-system case studies",
    focus: "Turn isolated concepts into fluent interview narratives.",
    lessons: [
      {
        day: "Day 1",
        title: "Structure your answer like a staff engineer",
        outcome: "Present scope, constraints, architecture, and trade-offs in a crisp sequence.",
        depth: "Move from clarifying questions to APIs, capacity, data model, scaling plan, and failure analysis without losing the interviewer.",
        drills: [
          "Practice a 3-minute design kickoff.",
          "Create a reusable answer template for large systems.",
        ],
        advancedNote: "Depth here is about pacing: reveal complexity only when it answers a pressure point instead of dumping every component at once.",
        checkpoint: "What do you say in the first two minutes that signals senior-level thinking?",
      },
      {
        day: "Day 2",
        title: "Case study: global chat with fan-out and presence",
        outcome: "Blend low-latency messaging, ordering limits, and connection management into one story.",
        depth: "Reason through websocket gateways, message durability, unread state, fan-out, and presence staleness boundaries.",
        drills: [
          "Choose where to keep connection state.",
          "Explain ordering guarantees inside and across rooms.",
        ],
        advancedNote: "Push beyond basics by discussing reconnect storms, offline delivery, and device synchronization semantics.",
        checkpoint: "How would you keep presence data cheap without making it misleading?",
      },
      {
        day: "Day 3",
        title: "Case study: collaborative document editing",
        outcome: "Explain concurrency control, intent preservation, and storage for shared editing systems.",
        depth: "Contrast operational transform and CRDT mental models, then map them to session coordination and persistence.",
        drills: [
          "Define what must be strongly consistent versus eventually merged.",
          "Discuss recovery after a client reconnects with divergent edits.",
        ],
        advancedNote: "Strong answers mention server-assigned epochs, rebasing, and why document storage and real-time sync have different optimization targets.",
        checkpoint: "What part of collaborative editing is hardest to fake in an interview answer?",
      },
      {
        day: "Day 4",
        title: "Case study: multi-tenant search platform",
        outcome: "Design indexing, query serving, relevance updates, and tenant isolation under heavy ingest.",
        depth: "Separate ingest path, segment merges, ranking signals, and query fan-out while accounting for freshness and cost.",
        drills: [
          "Plan index partitioning for many small tenants and a few huge tenants.",
          "Explain how relevance experiments affect storage and serving.",
        ],
        advancedNote: "Depth comes from describing merge debt, query caches, and how freshness SLAs differ for writes versus ranking features.",
        checkpoint: "How do you stop one tenant’s indexing burst from hurting everyone’s search latency?",
      },
      {
        day: "Day 5",
        title: "Final simulation: design under changing constraints",
        outcome: "Practice reacting when the interviewer introduces new scale, consistency, or cost constraints mid-solution.",
        depth: "Revisit a prior design and deliberately change traffic shape, region count, or correctness requirements, then explain the architectural pivot.",
        drills: [
          "Redo your favorite case study with 10x write load.",
          "Re-answer a design after adding strict audit requirements.",
        ],
        advancedNote: "Senior-level polish is the ability to say what you would not change, which protects clarity while still adapting the design.",
        checkpoint: "How do you change direction without making your earlier design sound wrong?",
      },
    ],
  },
];
